use std::collections::BTreeMap;
use std::env;
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use aio_dsh_protocol::ProtocolSchema;
use serde_json::{Map, Value};
use sha2::{Digest, Sha256};

struct Artifact {
    relative_path: &'static str,
    bytes: Vec<u8>,
}

fn main() {
    if let Err(message) = run() {
        eprintln!("{message}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let check = match env::args().skip(1).collect::<Vec<_>>().as_slice() {
        [] => false,
        [flag] if flag == "--check" => true,
        arguments => {
            return Err(format!(
                "usage: generate [--check]; unexpected arguments: {arguments:?}"
            ));
        }
    };

    let repository_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| "protocol crate is not nested under the repository root".to_owned())?;
    let artifacts = generated_artifacts()?;

    if check {
        let drifted = artifacts
            .iter()
            .filter_map(|artifact| {
                let path = repository_root.join(artifact.relative_path);
                match fs::read(path) {
                    Ok(current) if current == artifact.bytes => None,
                    _ => Some(artifact.relative_path),
                }
            })
            .collect::<Vec<_>>();
        if drifted.is_empty() {
            return Ok(());
        }
        return Err(format!(
            "generated protocol drift: {}\nrun `bun run generate:protocol` to refresh artifacts",
            drifted.join(", ")
        ));
    }

    for artifact in artifacts {
        write_atomic(
            &repository_root.join(artifact.relative_path),
            &artifact.bytes,
        )?;
    }
    Ok(())
}

fn generated_artifacts() -> Result<[Artifact; 3], String> {
    let schema = schemars::schema_for!(ProtocolSchema);
    let canonical_schema = canonicalize(
        serde_json::to_value(schema).map_err(|error| format!("serialize schema: {error}"))?,
    );
    let mut schema_bytes = serde_json::to_vec(&canonical_schema)
        .map_err(|error| format!("encode canonical schema: {error}"))?;
    schema_bytes.push(b'\n');

    let contract_hash = format!("{:x}", Sha256::digest(&schema_bytes));
    let declarations = typescript_declarations(&canonical_schema, &contract_hash)?;

    Ok([
        Artifact {
            relative_path: "generated/protocol.schema.json",
            bytes: schema_bytes,
        },
        Artifact {
            relative_path: "generated/protocol.d.ts",
            bytes: declarations.into_bytes(),
        },
        Artifact {
            relative_path: "generated/protocol.sha256",
            bytes: contract_hash.into_bytes(),
        },
    ])
}

fn canonicalize(value: Value) -> Value {
    match value {
        Value::Object(object) => {
            let sorted = object
                .into_iter()
                .map(|(key, value)| (key, canonicalize(value)))
                .collect::<BTreeMap<_, _>>();
            Value::Object(sorted.into_iter().collect::<Map<_, _>>())
        }
        Value::Array(values) => Value::Array(values.into_iter().map(canonicalize).collect()),
        primitive => primitive,
    }
}

fn typescript_declarations(schema: &Value, contract_hash: &str) -> Result<String, String> {
    let definitions = schema
        .get("$defs")
        .and_then(Value::as_object)
        .ok_or_else(|| "protocol schema is missing $defs".to_owned())?;
    let root_name = schema
        .get("title")
        .and_then(Value::as_str)
        .unwrap_or("ProtocolSchema");

    let mut output =
        String::from("/* This file is generated by aio-dsh-protocol. Do not edit. */\n\n");
    output.push_str(&format!(
        "export const CONTRACT_HASH = \"{contract_hash}\";\n\n"
    ));
    for (name, definition) in definitions {
        output.push_str(&format!(
            "export type {} = {};\n\n",
            type_name(name),
            ts_type(definition, 0)?
        ));
    }
    output.push_str(&format!(
        "export type {} = {};\n",
        type_name(root_name),
        ts_type(schema, 0)?
    ));
    Ok(output)
}

fn ts_type(schema: &Value, indent: usize) -> Result<String, String> {
    match schema {
        Value::Bool(true) => return Ok("unknown".to_owned()),
        Value::Bool(false) => return Ok("never".to_owned()),
        Value::Object(_) => {}
        _ => return Err("schema node must be an object or boolean".to_owned()),
    }

    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let name = reference
            .strip_prefix("#/$defs/")
            .ok_or_else(|| format!("unsupported schema reference {reference:?}"))?;
        return Ok(type_name(name));
    }
    if let Some(value) = schema.get("const") {
        return ts_literal(value);
    }
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        return join_schema_types(values.iter().map(ts_literal), " | ");
    }
    for (keyword, separator) in [("oneOf", " | "), ("anyOf", " | "), ("allOf", " & ")] {
        if let Some(variants) = schema.get(keyword).and_then(Value::as_array) {
            return join_schema_types(
                variants
                    .iter()
                    .map(|variant| ts_type(variant, indent).map(parenthesize_composite)),
                separator,
            );
        }
    }

    match schema.get("type") {
        Some(Value::Array(types)) => join_schema_types(
            types.iter().map(|value| {
                ts_type(
                    &Value::Object(Map::from_iter([("type".to_owned(), value.clone())])),
                    indent,
                )
            }),
            " | ",
        ),
        Some(Value::String(kind)) => match kind.as_str() {
            "null" => Ok("null".to_owned()),
            "boolean" => Ok("boolean".to_owned()),
            "integer" | "number" => Ok("number".to_owned()),
            "string" => Ok("string".to_owned()),
            "array" => {
                let item = schema.get("items").unwrap_or(&Value::Bool(true));
                Ok(format!("Array<{}>", ts_type(item, indent)?))
            }
            "object" => ts_object(schema, indent),
            unsupported => Err(format!("unsupported JSON Schema type {unsupported:?}")),
        },
        None if schema.get("properties").is_some()
            || schema.get("additionalProperties").is_some() =>
        {
            ts_object(schema, indent)
        }
        None => Ok("unknown".to_owned()),
        Some(other) => Err(format!("invalid JSON Schema type {other}")),
    }
}

fn ts_object(schema: &Value, indent: usize) -> Result<String, String> {
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let required = schema
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<std::collections::BTreeSet<_>>();
    let next_indent = indent + 2;
    let padding = " ".repeat(next_indent);
    let closing_padding = " ".repeat(indent);
    let mut members = Vec::new();

    for (name, property_schema) in properties {
        let optional = if required.contains(name.as_str()) {
            ""
        } else {
            "?"
        };
        members.push(format!(
            "{padding}{}{optional}: {};",
            property_name(&name),
            ts_type(&property_schema, next_indent)?
        ));
    }

    match schema.get("additionalProperties") {
        Some(Value::Bool(false)) | None if !members.is_empty() => {}
        Some(Value::Bool(false)) => {}
        Some(Value::Bool(true)) | None => {
            members.push(format!("{padding}[key: string]: unknown;"));
        }
        Some(additional) => members.push(format!(
            "{padding}[key: string]: {};",
            ts_type(additional, next_indent)?
        )),
    }

    if members.is_empty() {
        return Ok("Record<string, never>".to_owned());
    }
    Ok(format!("{{\n{}\n{closing_padding}}}", members.join("\n")))
}

fn ts_literal(value: &Value) -> Result<String, String> {
    match value {
        Value::Null => Ok("null".to_owned()),
        Value::Bool(value) => Ok(value.to_string()),
        Value::Number(value) => Ok(value.to_string()),
        Value::String(value) => serde_json::to_string(value)
            .map_err(|error| format!("encode TypeScript string literal: {error}")),
        _ => Err(format!("unsupported TypeScript literal {value}")),
    }
}

fn join_schema_types<I>(types: I, separator: &str) -> Result<String, String>
where
    I: IntoIterator<Item = Result<String, String>>,
{
    let values = types.into_iter().collect::<Result<Vec<_>, _>>()?;
    if values.is_empty() {
        Ok("never".to_owned())
    } else {
        Ok(values.join(separator))
    }
}

fn parenthesize_composite(value: String) -> String {
    if value.contains('\n') || value.contains(" | ") || value.contains(" & ") {
        format!("({value})")
    } else {
        value
    }
}

fn type_name(value: &str) -> String {
    value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect()
}

fn property_name(value: &str) -> String {
    let mut characters = value.chars();
    let is_identifier = characters
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic() || first == '_')
        && characters.all(|character| character.is_ascii_alphanumeric() || character == '_');
    if is_identifier {
        value.to_owned()
    } else {
        serde_json::to_string(value).expect("JSON property names are serializable")
    }
}

fn write_atomic(path: &Path, bytes: &[u8]) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| format!("generated path has no parent: {}", path.display()))?;
    fs::create_dir_all(parent)
        .map_err(|error| format!("create generated directory {}: {error}", parent.display()))?;
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| format!("generated path has no UTF-8 file name: {}", path.display()))?;
    let temporary = parent.join(format!(".{file_name}.tmp"));

    let result = (|| {
        let mut file = OpenOptions::new()
            .create(true)
            .truncate(true)
            .write(true)
            .open(&temporary)
            .map_err(|error| format!("open temporary artifact {}: {error}", temporary.display()))?;
        file.write_all(bytes).map_err(|error| {
            format!("write temporary artifact {}: {error}", temporary.display())
        })?;
        file.sync_all()
            .map_err(|error| format!("sync temporary artifact {}: {error}", temporary.display()))?;
        drop(file);
        fs::rename(&temporary, path).map_err(|error| {
            format!(
                "replace generated artifact {} with {}: {error}",
                path.display(),
                temporary.display()
            )
        })
    })();

    if result.is_err() {
        let _ = fs::remove_file(PathBuf::from(&temporary));
    }
    result
}
